export const OrderType = {
    SignNew: 'km',
    Renewal: 'gh',
    Upgrade: 'nc',
    Appendix: 'pl'
}

interface SaleOrderData {
    access_token: boolean,
    access_url: string,
    access_warning: string,
    activity_date_deadline: boolean,
    activity_exception_decoration: boolean,
    activity_exception_icon: boolean,
    activity_ids: Array<string>,
    activity_state: boolean,
    activity_summary: boolean,
    activity_type_id: boolean,
    activity_user_id: boolean,
    adv_budget_ratio: number,
    amount_by_group: Array<string>,
    amount_tax: number,
    amount_total: number,
    amount_undiscounted: number,
    amount_untaxed: number,
    analytic_account_id: number,
    applied_coupon_ids: Array<string>,
    authorized_transaction_ids: Array<string>,
    campaign_id: boolean,
    carrier_id: boolean,
    check_order_promotion: boolean,
    client_order_ref: boolean,
    code_promo_program_id: boolean,
    commitment_date: boolean,
    company_id: number,
    create_date: Date,
    create_uid: number,
    currency_id: number,
    currency_rate: number,
    date_order: Date,
    delivery_count: number,
    delivery_message: boolean,
    delivery_rating_success: boolean,
    delivery_set: false,
    department_id: boolean,
    display_name: string,
    dms_contract_code: string,
    dms_id: number,
    dms_url: string,
    effective_date: boolean,
    expected_date: Date,
    fiscal_position_id: boolean,
    generated_coupon_ids: Array<string>
    id: number,
    incoterm: boolean,
    invoice_count: number,
    invoice_ids: Array<string>,
    invoice_status: string,
    is_all_service: boolean,
    is_expired: boolean,
    list_promotion: boolean,
    margin: number,
    medium_id: boolean,
    message_attachment_count: number,
    message_channel_ids: Array<string>,
    message_follower_ids: Array<string>,
    message_has_error: boolean,
    message_has_error_counter: number,
    message_has_sms_error: boolean,
    message_ids: Array<string>,
    message_is_follower: boolean,
    message_main_attachment_id: boolean,
    message_needaction: boolean,
    message_needaction_counter: number,
    message_partner_ids: Array<string>,
    message_unread: boolean,
    message_unread_counter: number,
    name: string,
    no_code_promo_program_ids: Array<string>,
    note: string,
    opportunity_id: boolean,
    order_line: Array<string>,
    origin: boolean,
    partner_id: number,
    partner_invoice_id: number,
    partner_shipping_id: number,
    payment_term_id: number
    picking_ids: Array<string>,
    picking_policy: string,
    pricelist_id: number,
    procurement_group_id: boolean,
    promo_code: boolean,
    purchase_order_count: number,
    recompute_delivery_price: boolean,
    reference: boolean
    remaining_validity_days: number,
    require_payment: boolean,
    require_signature: boolean,
    reward_amount: number,
    sale_order_option_ids: Array<string>,
    signature: boolean,
    signed_by: boolean,
    signed_on: boolean,
    source_id: boolean,
    state: string,
    stock_move_line_ids: Array<string>,
    subscription_count: number,
    subscription_management: string,
    tag_ids: Array<string>,
    team_id: number,
    transaction_ids: Array<string>,
    type_name: string,
    user_id: number,
    validity_date: string,
    warehouse_id: number,
    website_message_ids: Array<string>,
    write_date: string,
    write_uid: number,
    x_item_offer: boolean,
    x_list_gift_promotion: string,
    x_tong_nguyen_gia: number,
    z_acc_number: boolean,
    z_amount_paid: number,
    z_bank: boolean,
    z_bao_co_count: number,
    z_bonus_product_ids: Array<string>,
    z_category_ids: Array<string>,
    z_condition_type: string,
    z_contract_expiry_date: string | false,
    z_coordination: number,
    z_coordination_support: boolean,
    z_customer_id_old: boolean,
    z_deputy_id: {
        id: number | false,
        name: string | false
    },
    z_dms_sale: number,
    z_edit_button: boolean,
    z_feedback_date: boolean,
    z_fnb_id: boolean | number,
    z_industries_id: boolean,
    z_invoice_address: string,
    is_display_fnb_id: boolean,
    z_sale_template_category_name: boolean | string,
    is_display_website_web: boolean,
    is_display_website_pos: boolean,
    z_website_web: boolean | string,
    z_website_pos: boolean | string,
    z_is_effect: string,
    z_list_promo_program: boolean,
    z_opportunity_code: string,
    z_order_type: false | 'km' | 'gh' | 'nc' | 'pl',
    z_original_manage_domain_ids: Array<string>,
    z_original_order_id: any,

    z_partner_city_id: number,
    z_partner_code: string,
    z_partner_district_id: number,
    z_partner_formal_title: number,
    z_partner_job_tax: false | string,
    z_partner_mail: string,
    z_partner_name: string,
    z_partner_phone: string,
    z_partner_private_code: any,
    z_partner_represent_address: any,
    z_partner_represent_birthday: any,
    z_partner_represent_email: any,
    z_partner_represent_formal: any,
    z_partner_represent_job: any,
    z_partner_represent_name: any,
    z_partner_represent_phone: any
    z_partner_represent_private_code: any,
    z_partner_street: false | string,
    z_partner_type: string,
    z_partner_ward_id: number,
    z_payment_ids: Array<string>,
    z_pl_ids: Array<string>,
    z_program_template_id: boolean,
    z_renewal_sale: boolean,
    z_sale_support: number,
    z_sale_support_2: number,
    z_shipping_address: string,
    z_sign_day: Date,
    z_sol_cost_item_ids: string,
    z_thu_count: number,
    z_transference_status: string,
    z_workflow_deployment: string,
    sale_order_template_id: {
        id: number | false,
        name: string | false
    },
    z_manage_domain_ids: {
        id: number | false,
        name: string | false
    }[]
    __last_update: Date
}

interface LineData {
    analytic_line_ids: Array<string>,
    analytic_tag_ids: Array<string>,
    company_id: number,
    coupon_program_ids: Array<string>,
    create_date: Date,
    create_uid: number,
    currency_id: number,
    customer_lead: number,
    discount: number,
    display_name: string,
    display_qty_widget: boolean,
    display_type: boolean,
    dms_id: number,
    expense_cost_item_id: number,
    free_qty_today: number,
    id: number,
    income_cost_item_id: number,
    invoice_lines: Array<string>,
    invoice_status: string,
    is_delivery: boolean,
    is_downpayment: boolean,
    is_expense: boolean,
    is_mto: boolean,
    is_reward_line: boolean,
    margin: number,
    move_ids: Array<string>,
    name: string,
    order_id: number,
    order_partner_id: number,
    order_price_promotion_id: number,
    price_reduce: number,
    price_reduce_taxexcl: number,
    price_reduce_taxinc: number,
    price_subtotal: number,
    price_tax: number,
    price_total: number,
    price_unit: number,
    product_custom_attribute_value_ids: Array<string>,
    product_template_id: {
        id: number | false,
        name: string | false
    },
    product_id: number,
    product_no_variant_attribute_value_ids: Array<string>,
    product_packaging: boolean,
    product_qty: number,
    product_type: string,
    product_uom: {
        id: number,
        name: string
    },
    product_uom_category_id: number,
    product_uom_qty: number,
    product_updatable: boolean,
    promotion_id: number,
    promotion_remain_qty: number,
    purchase_line_count: number,
    purchase_line_ids: Array<string>,
    purchase_price: number,
    qty_available_today: number,
    qty_delivered: number,
    qty_delivered_manual: number,
    qty_delivered_method: string,
    qty_invoiced: number,
    qty_to_deliver: number,
    qty_to_invoice: number,
    recompute_delivery_price: boolean,
    route_id: boolean,
    sale_order_option_ids: Array<string>,
    salesman_id: number,
    scheduled_date: boolean,
    sequence: number,
    state: string,
    subscription_id: boolean,
    tax_id: Array<string>,
    untaxed_amount_invoiced: number,
    untaxed_amount_to_invoice: number,
    virtual_available_at_date: number,
    warehouse_id: boolean,
    write_date: Date,
    write_uid: number,
    x_is_promotion: number,
    x_sales_price: number,
    z_amount_discount: number,
    z_is_edit: boolean,
    z_manage_domain_type: string,
    z_product_tmpl_id: boolean,
    z_so_id: boolean,
    z_template_line_id: boolean,
    z_website_name: string,
    z_website_type: boolean,
    __last_update: Date
}

interface LotData {
    name: string,
    lot_id: string,
    qty_done: number,
    product_uom: string,
    sale_start_warranty_date: string,
    sale_expiration_warranty_date: string,
    contractType: string,
    website: string | number
}

interface Contract {
    so_data: SaleOrderData,
    lines_data: Array<LineData>,
    lot_data: Array<LotData>
}

export type {
    SaleOrderData,
    LineData,
    LotData,
    Contract
}
